### ISSUE TITLE
Screen resolution support

### ISSUE THREAD

**Issue by Y1hsiaochunnn** [espressif/esp-ui#1]
Hi, @Lzw655 
I wanna adapt to waveshare 8, 10.1 display screen, currently these display resolution is 1280x800, is it possible to add **espressif/esp-ui-phone_1280_800_stylesheet**  to support it?

**Comment by Lzw655** [comment]
Hi @Y1hsiaochunnn,  thank you for using this library. We have added `1280x800` to the target plan, along with `320x240`, `240x320`, and `800x1280`. You will be notified once it is completed.

**Comment by Lzw655** [comment]
Record in #5 .
