### ISSUE TITLE
How to build new application on project

### ISSUE THREAD

**Issue by isthaison** [espressif/esp-ui#3]

**Comment by isthaison** [comment]
![image](https://github.com/user-attachments/assets/12ad94a5-8719-4757-9ff1-89dd4114b423)

**Comment by isthaison** [comment]
Do you make simple with new repositories?

**Comment by isthaison** [comment]
![image](https://github.com/user-attachments/assets/d35d983c-5471-4592-88ff-6763b82328e1)
@Lzw655  Can you make a specific article or a more complete template?

**Comment by Lzw655** [comment]
Hi @isthaison, Sorry for not getting back to you sooner. Has your issue been resolved?

**Comment by isthaison** [comment]
It's OK. 😂😂
